org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=false
org.gradle.java.home=/Users/codefliesgd/.jdks/jdk-17.0.20.1+1/Contents/Home
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process

